export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const UPDATE_PASSWORD_START = 'UPDATE_PASSWORD_START'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const CHECK_AUTH_STATE_START = 'CHECK_AUTH_STATE_START';
export const CHECK_AUTH_STATE_SUCCESS = 'CHECK_AUTH_STATE_SUCCESS';

export const UPDATE_ACCOUNT_START = 'UPDATE_ACCOUNT_START';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';

export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';

export const FETCH_GAMES_START = 'FETCH_GAMES_START';
export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';
export const FETCH_GAMES_FAIL = 'FETCH_GAMES_FAIL';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const CLEAR_CURRENT_GAME = 'CLEAR_CURRENT_GAME';

export const ADD_NUMBER = 'ADD_NUMBER';
export const REMOVE_NUMBER = 'REMOVE_NUMBER';
export const CLEAR_NUMBERS = 'CLEAR_NUMBERS';
export const COMPLETE_NUMBERS = 'COMPLETE_NUMBERS';
export const SHOW_CART = 'SHOW_CART'
export const HIDE_CART = 'HIDE_CART'

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const FILTER_BETS = 'FILTER_BETS';
export const UNFILTER_BETS = 'UNFILTER_BETS';

export const SAVE_BETS_START = 'SAVE_BETS_START';
export const SAVE_BETS_SUCCESS = 'SAVE_BETS_SUCCESS';
export const SAVE_BETS_FAIL = 'SAVE_BETS_FAIL';

export const FETCH_BETS_START = 'FETCH_BETS_START';
export const FETCH_BETS_SUCCESS = 'FETCH_BETS_SUCCESS';
export const FETCH_BETS_FAIL = 'FETCH_BETS_FAIL';